### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by shirubana** [NREL/PV_ICE#12]
Well, I'm sure at some point I did this correctly because even Heather installed it <2 months ago, but now it's not working. 

It used to work by cloning, navigating to folder and then doing a pip install -e . 

Now that doesnt even work. 
Much less the pyppi, been stuck on that forever...

 ![image](https://user-images.githubusercontent.com/22824806/112312373-5c6dfa00-8c6c-11eb-83e9-a649d5b1a6dc.png)

![image](https://user-images.githubusercontent.com/22824806/112313100-1c5b4700-8c6d-11eb-9f0f-900af7adbcb7.png)

**Comment by shirubana** [comment]
@mdeceglie can you help me with this please? I'm stuck :(

**Comment by kanderso-nrel** [comment]
@shirubana newer versions of pip switched to "isolated builds", which means the files like `versioneer.py` next to `setup.py` aren't available by default (`ModuleNotFoundError`).  So to make them available you add the folder to `sys.path` -- this change to `setup.py` made `pip install .` work for me:

```diff
 from codecs import open
 from os import path

-import versioneer

 here = path.abspath(path.dirname(__file__))

+import sys
+sys.path.insert(0, here)  # make sure local files are available to an isolated build
+import versioneer
+
 # Get the long description from the README file
 with open(path.join(here, 'README.md'), encoding='utf-8') as f:
     long_description = f.read()
```

**Comment by shirubana** [comment]
You're so wise!!!!!!!!!! Thank you . okay problem 1 finished. PHEW time to try the Pypi thing now.
